#############################################################################
# Makefile for building: VentiApp
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  VentiApp.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile VentiApp.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = VentiApp1.0.0
DISTDIR = /home/pi/VentiApp/.tmp/VentiApp1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -L/usr/local/include -lwiringPi -L/usr/local/lib -lpigpiod_if2 -lQt5Widgets -lQt5Gui -lQt5Core -lGLESv2 -lpthread -latomic 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainmenu.cpp \
		mainscreen.cpp \
		mainwindow.cpp \
		mylabelanimated.cpp \
		mywidgetanimated.cpp \
		optiondatetime.cpp \
		optioncalibration.cpp \
		globalfunctions.cpp \
		optionalarmlimit.cpp \
		optiongeneral.cpp \
		DrvI2C.cpp \
		DrvAdc.cpp \
		IEEE754.cpp \
		DrvGauge.cpp \
		DrvGpio.cpp \
		DrvRtc.cpp \
		ThrInput.cpp \
		Time.cpp \
		optionsetdate.cpp \
		optionsettime.cpp \
		processesclass.cpp qrc_assets.cpp \
		moc_mainmenu.cpp \
		moc_mainscreen.cpp \
		moc_mainwindow.cpp \
		moc_mylabelanimated.cpp \
		moc_mywidgetanimated.cpp \
		moc_optiondatetime.cpp \
		moc_optioncalibration.cpp \
		moc_globalfunctions.cpp \
		moc_optionalarmlimit.cpp \
		moc_optiongeneral.cpp \
		moc_ThrInput.cpp \
		moc_optionsetdate.cpp \
		moc_optionsettime.cpp
OBJECTS       = main.o \
		mainmenu.o \
		mainscreen.o \
		mainwindow.o \
		mylabelanimated.o \
		mywidgetanimated.o \
		optiondatetime.o \
		optioncalibration.o \
		globalfunctions.o \
		optionalarmlimit.o \
		optiongeneral.o \
		DrvI2C.o \
		DrvAdc.o \
		IEEE754.o \
		DrvGauge.o \
		DrvGpio.o \
		DrvRtc.o \
		ThrInput.o \
		Time.o \
		optionsetdate.o \
		optionsettime.o \
		processesclass.o \
		qrc_assets.o \
		moc_mainmenu.o \
		moc_mainscreen.o \
		moc_mainwindow.o \
		moc_mylabelanimated.o \
		moc_mywidgetanimated.o \
		moc_optiondatetime.o \
		moc_optioncalibration.o \
		moc_globalfunctions.o \
		moc_optionalarmlimit.o \
		moc_optiongeneral.o \
		moc_ThrInput.o \
		moc_optionsetdate.o \
		moc_optionsettime.o
DIST          = /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		VentiApp.pro mainmenu.h \
		mainscreen.h \
		mainwindow.h \
		mylabelanimated.h \
		mywidgetanimated.h \
		optiondatetime.h \
		optioncalibration.h \
		globalfunctions.h \
		optionalarmlimit.h \
		optiongeneral.h \
		DrvI2C.h \
		DrvAdc.h \
		IEEE754.h \
		DrvGauge.h \
		DrvGpio.h \
		DrvRtc.h \
		GMacros.h \
		Singleton.h \
		QMath.h \
		ThrInput.h \
		Time.h \
		optionsetdate.h \
		optionsettime.h \
		processesclass.h main.cpp \
		mainmenu.cpp \
		mainscreen.cpp \
		mainwindow.cpp \
		mylabelanimated.cpp \
		mywidgetanimated.cpp \
		optiondatetime.cpp \
		optioncalibration.cpp \
		globalfunctions.cpp \
		optionalarmlimit.cpp \
		optiongeneral.cpp \
		DrvI2C.cpp \
		DrvAdc.cpp \
		IEEE754.cpp \
		DrvGauge.cpp \
		DrvGpio.cpp \
		DrvRtc.cpp \
		ThrInput.cpp \
		Time.cpp \
		optionsetdate.cpp \
		optionsettime.cpp \
		processesclass.cpp
QMAKE_TARGET  = VentiApp
DESTDIR       = 
TARGET        = VentiApp


first: all
####### Build rules

$(TARGET): ui_mainmenu.h ui_mainscreen.h ui_mainwindow.h ui_optiondatetime.h ui_optioncalibration.h ui_optionalarmlimit.h ui_optiongeneral.h ui_optionsetdate.h ui_optionsettime.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VentiApp.pro /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		VentiApp.pro \
		assets.qrc \
		/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Core.prl
	$(QMAKE) -o Makefile VentiApp.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf:
VentiApp.pro:
assets.qrc:
/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile VentiApp.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents assets.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainmenu.h mainscreen.h mainwindow.h mylabelanimated.h mywidgetanimated.h optiondatetime.h optioncalibration.h globalfunctions.h optionalarmlimit.h optiongeneral.h DrvI2C.h DrvAdc.h IEEE754.h DrvGauge.h DrvGpio.h DrvRtc.h GMacros.h Singleton.h QMath.h ThrInput.h Time.h optionsetdate.h optionsettime.h processesclass.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainmenu.cpp mainscreen.cpp mainwindow.cpp mylabelanimated.cpp mywidgetanimated.cpp optiondatetime.cpp optioncalibration.cpp globalfunctions.cpp optionalarmlimit.cpp optiongeneral.cpp DrvI2C.cpp DrvAdc.cpp IEEE754.cpp DrvGauge.cpp DrvGpio.cpp DrvRtc.cpp ThrInput.cpp Time.cpp optionsetdate.cpp optionsettime.cpp processesclass.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainmenu.ui mainscreen.ui mainwindow.ui optiondatetime.ui optioncalibration.ui optionalarmlimit.ui optiongeneral.ui optionsetdate.ui optionsettime.ui optionsetdate.ui optionsettime.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_assets.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_assets.cpp
qrc_assets.cpp: assets.qrc \
		/usr/lib/qt5/bin/rcc \
		icons/screen_logo.png \
		icons/main_menu/general_menu/general_back_button.png \
		icons/main_menu/general_menu/general_button.png \
		icons/main_menu/general_menu/battery_state_button.png \
		icons/main_menu/general_menu/header_general_menu.png \
		icons/main_menu/general_menu/lenguage_button.png \
		icons/main_menu/general_menu/about_button.png \
		icons/main_menu/general_menu/footer_general_menu.png \
		icons/main_menu/alarm_limit_menu/background_alarm_limit_menu.png \
		icons/main_menu/alarm_limit_menu/alarm_limit_button.png \
		icons/main_menu/alarm_limit_menu/header_alarm_limit_menu.png \
		icons/main_menu/date_time_menu/header_date_time_menu.png \
		icons/main_menu/date_time_menu/12_hours_off.png \
		icons/main_menu/date_time_menu/define_hour_button.png \
		icons/main_menu/date_time_menu/date_format_button.png \
		icons/main_menu/date_time_menu/24_hours_off.png \
		icons/main_menu/date_time_menu/date_time_back_button.png \
		icons/main_menu/date_time_menu/24_hours_on.png \
		icons/main_menu/date_time_menu/define_date_button.png \
		icons/main_menu/date_time_menu/12_hours_on.png \
		icons/main_menu/date_time_menu/date_time_button.png \
		icons/main_menu/calibration_menu/ok.png \
		icons/main_menu/calibration_menu/error.png \
		icons/main_menu/calibration_menu/header_calibration_menu.png \
		icons/main_menu/calibration_menu/calibration_button.png \
		icons/main_menu/calibration_menu/background_calibration_menu.png \
		icons/main_menu/calibration_menu/footer_menu_calibration.png \
		icons/main_menu/lenguage_menu/header_lenguage_menu.png \
		icons/general/battery_50.png \
		icons/general/empty_button.png \
		icons/general/down_arrow.png \
		icons/general/next_button.png \
		icons/general/battery_75.png \
		icons/general/battery_100.png \
		icons/general/battery_low.png \
		icons/general/left_arrow.png \
		icons/general/logo.png \
		icons/general/save_button.png \
		icons/general/start_button.png \
		icons/general/cancel_button.png \
		icons/general/battery_25.png \
		icons/general/exit_button.png \
		icons/general/repeat_button.png \
		icons/general/fondo_transparente.png \
		icons/general/up_arrow.png \
		icons/main_screen/widget_settings_off.png \
		icons/main_screen/background.png \
		icons/main_screen/widget_settings_on.png \
		icons/main_screen/header.png
	/usr/lib/qt5/bin/rcc -name assets assets.qrc -o qrc_assets.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainmenu.cpp moc_mainscreen.cpp moc_mainwindow.cpp moc_mylabelanimated.cpp moc_mywidgetanimated.cpp moc_optiondatetime.cpp moc_optioncalibration.cpp moc_globalfunctions.cpp moc_optionalarmlimit.cpp moc_optiongeneral.cpp moc_ThrInput.cpp moc_optionsetdate.cpp moc_optionsettime.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainmenu.cpp moc_mainscreen.cpp moc_mainwindow.cpp moc_mylabelanimated.cpp moc_mywidgetanimated.cpp moc_optiondatetime.cpp moc_optioncalibration.cpp moc_globalfunctions.cpp moc_optionalarmlimit.cpp moc_optiongeneral.cpp moc_ThrInput.cpp moc_optionsetdate.cpp moc_optionsettime.cpp
moc_mainmenu.cpp: mainmenu.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include mainmenu.h -o moc_mainmenu.cpp

moc_mainscreen.cpp: mainmenu.h \
		mainscreen.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include mainscreen.h -o moc_mainscreen.cpp

moc_mainwindow.cpp: mainscreen.h \
		mainmenu.h \
		ThrInput.h \
		Singleton.h \
		GMacros.h \
		DrvAdc.h \
		DrvI2C.h \
		DrvRtc.h \
		DrvGauge.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_mylabelanimated.cpp: mylabelanimated.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include mylabelanimated.h -o moc_mylabelanimated.cpp

moc_mywidgetanimated.cpp: mywidgetanimated.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include mywidgetanimated.h -o moc_mywidgetanimated.cpp

moc_optiondatetime.cpp: optiondatetime.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include optiondatetime.h -o moc_optiondatetime.cpp

moc_optioncalibration.cpp: optioncalibration.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include optioncalibration.h -o moc_optioncalibration.cpp

moc_globalfunctions.cpp: globalfunctions.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include globalfunctions.h -o moc_globalfunctions.cpp

moc_optionalarmlimit.cpp: optionalarmlimit.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include optionalarmlimit.h -o moc_optionalarmlimit.cpp

moc_optiongeneral.cpp: optiongeneral.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include optiongeneral.h -o moc_optiongeneral.cpp

moc_ThrInput.cpp: Singleton.h \
		GMacros.h \
		DrvAdc.h \
		DrvI2C.h \
		DrvRtc.h \
		DrvGauge.h \
		ThrInput.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include ThrInput.h -o moc_ThrInput.cpp

moc_optionsetdate.cpp: optionsetdate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include optionsetdate.h -o moc_optionsetdate.cpp

moc_optionsettime.cpp: optionsettime.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/VentiApp/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/home/pi/VentiApp -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include optionsettime.h -o moc_optionsettime.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainmenu.h ui_mainscreen.h ui_mainwindow.h ui_optiondatetime.h ui_optioncalibration.h ui_optionalarmlimit.h ui_optiongeneral.h ui_optionsetdate.h ui_optionsettime.h ui_optionsetdate.h ui_optionsettime.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainmenu.h ui_mainscreen.h ui_mainwindow.h ui_optiondatetime.h ui_optioncalibration.h ui_optionalarmlimit.h ui_optiongeneral.h ui_optionsetdate.h ui_optionsettime.h ui_optionsetdate.h ui_optionsettime.h
ui_mainmenu.h: mainmenu.ui \
		/usr/lib/qt5/bin/uic \
		mylabelanimated.h \
		mywidgetanimated.h
	/usr/lib/qt5/bin/uic mainmenu.ui -o ui_mainmenu.h

ui_mainscreen.h: mainscreen.ui \
		/usr/lib/qt5/bin/uic \
		mywidgetanimated.h
	/usr/lib/qt5/bin/uic mainscreen.ui -o ui_mainscreen.h

ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_optiondatetime.h: optiondatetime.ui \
		/usr/lib/qt5/bin/uic \
		mylabelanimated.h
	/usr/lib/qt5/bin/uic optiondatetime.ui -o ui_optiondatetime.h

ui_optioncalibration.h: optioncalibration.ui \
		/usr/lib/qt5/bin/uic \
		mylabelanimated.h
	/usr/lib/qt5/bin/uic optioncalibration.ui -o ui_optioncalibration.h

ui_optionalarmlimit.h: optionalarmlimit.ui \
		/usr/lib/qt5/bin/uic \
		mylabelanimated.h
	/usr/lib/qt5/bin/uic optionalarmlimit.ui -o ui_optionalarmlimit.h

ui_optiongeneral.h: optiongeneral.ui \
		/usr/lib/qt5/bin/uic \
		mylabelanimated.h
	/usr/lib/qt5/bin/uic optiongeneral.ui -o ui_optiongeneral.h

ui_optionsetdate.h: optionsetdate.ui \
		/usr/lib/qt5/bin/uic \
		mylabelanimated.h
	/usr/lib/qt5/bin/uic optionsetdate.ui -o ui_optionsetdate.h

ui_optionsettime.h: optionsettime.ui \
		/usr/lib/qt5/bin/uic \
		mylabelanimated.h
	/usr/lib/qt5/bin/uic optionsettime.ui -o ui_optionsettime.h

ui_optionsetdate.h: optionsetdate.ui \
		/usr/lib/qt5/bin/uic \
		mylabelanimated.h
	/usr/lib/qt5/bin/uic optionsetdate.ui -o ui_optionsetdate.h

ui_optionsettime.h: optionsettime.ui \
		/usr/lib/qt5/bin/uic \
		mylabelanimated.h
	/usr/lib/qt5/bin/uic optionsettime.ui -o ui_optionsettime.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		mainscreen.h \
		mainmenu.h \
		ThrInput.h \
		Singleton.h \
		GMacros.h \
		DrvAdc.h \
		DrvI2C.h \
		DrvRtc.h \
		DrvGauge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainmenu.o: mainmenu.cpp mainmenu.h \
		ui_mainmenu.h \
		mylabelanimated.h \
		mywidgetanimated.h \
		optiondatetime.h \
		optioncalibration.h \
		optionalarmlimit.h \
		optiongeneral.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainmenu.o mainmenu.cpp

mainscreen.o: mainscreen.cpp mainscreen.h \
		mainmenu.h \
		ui_mainscreen.h \
		mywidgetanimated.h \
		globalfunctions.h \
		processesclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainscreen.o mainscreen.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		mainscreen.h \
		mainmenu.h \
		ThrInput.h \
		Singleton.h \
		GMacros.h \
		DrvAdc.h \
		DrvI2C.h \
		DrvRtc.h \
		DrvGauge.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mylabelanimated.o: mylabelanimated.cpp mylabelanimated.h \
		globalfunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mylabelanimated.o mylabelanimated.cpp

mywidgetanimated.o: mywidgetanimated.cpp mywidgetanimated.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mywidgetanimated.o mywidgetanimated.cpp

optiondatetime.o: optiondatetime.cpp optiondatetime.h \
		ui_optiondatetime.h \
		mylabelanimated.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optiondatetime.o optiondatetime.cpp

optioncalibration.o: optioncalibration.cpp optioncalibration.h \
		ui_optioncalibration.h \
		mylabelanimated.h \
		globalfunctions.h \
		mainscreen.h \
		mainmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optioncalibration.o optioncalibration.cpp

globalfunctions.o: globalfunctions.cpp globalfunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globalfunctions.o globalfunctions.cpp

optionalarmlimit.o: optionalarmlimit.cpp optionalarmlimit.h \
		ui_optionalarmlimit.h \
		mylabelanimated.h \
		globalfunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionalarmlimit.o optionalarmlimit.cpp

optiongeneral.o: optiongeneral.cpp optiongeneral.h \
		ui_optiongeneral.h \
		mylabelanimated.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optiongeneral.o optiongeneral.cpp

DrvI2C.o: DrvI2C.cpp DrvI2C.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DrvI2C.o DrvI2C.cpp

DrvAdc.o: DrvAdc.cpp DrvAdc.h \
		DrvI2C.h \
		ThrInput.h \
		Singleton.h \
		GMacros.h \
		DrvRtc.h \
		DrvGauge.h \
		IEEE754.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DrvAdc.o DrvAdc.cpp

IEEE754.o: IEEE754.cpp IEEE754.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IEEE754.o IEEE754.cpp

DrvGauge.o: DrvGauge.cpp DrvGauge.h \
		DrvI2C.h \
		IEEE754.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DrvGauge.o DrvGauge.cpp

DrvGpio.o: DrvGpio.cpp DrvGpio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DrvGpio.o DrvGpio.cpp

DrvRtc.o: DrvRtc.cpp DrvRtc.h \
		DrvI2C.h \
		ThrInput.h \
		Singleton.h \
		GMacros.h \
		DrvAdc.h \
		DrvGauge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DrvRtc.o DrvRtc.cpp

ThrInput.o: ThrInput.cpp ThrInput.h \
		Singleton.h \
		GMacros.h \
		DrvAdc.h \
		DrvI2C.h \
		DrvRtc.h \
		DrvGauge.h \
		IEEE754.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ThrInput.o ThrInput.cpp

Time.o: Time.cpp Time.h \
		QMath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Time.o Time.cpp

optionsetdate.o: optionsetdate.cpp optionsetdate.h \
		ui_optionsetdate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsetdate.o optionsetdate.cpp

optionsettime.o: optionsettime.cpp optionsettime.h \
		ui_optionsettime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsettime.o optionsettime.cpp

processesclass.o: processesclass.cpp processesclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processesclass.o processesclass.cpp

qrc_assets.o: qrc_assets.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_assets.o qrc_assets.cpp

moc_mainmenu.o: moc_mainmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainmenu.o moc_mainmenu.cpp

moc_mainscreen.o: moc_mainscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainscreen.o moc_mainscreen.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_mylabelanimated.o: moc_mylabelanimated.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mylabelanimated.o moc_mylabelanimated.cpp

moc_mywidgetanimated.o: moc_mywidgetanimated.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mywidgetanimated.o moc_mywidgetanimated.cpp

moc_optiondatetime.o: moc_optiondatetime.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optiondatetime.o moc_optiondatetime.cpp

moc_optioncalibration.o: moc_optioncalibration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optioncalibration.o moc_optioncalibration.cpp

moc_globalfunctions.o: moc_globalfunctions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_globalfunctions.o moc_globalfunctions.cpp

moc_optionalarmlimit.o: moc_optionalarmlimit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionalarmlimit.o moc_optionalarmlimit.cpp

moc_optiongeneral.o: moc_optiongeneral.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optiongeneral.o moc_optiongeneral.cpp

moc_ThrInput.o: moc_ThrInput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ThrInput.o moc_ThrInput.cpp

moc_optionsetdate.o: moc_optionsetdate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionsetdate.o moc_optionsetdate.cpp

moc_optionsettime.o: moc_optionsettime.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionsettime.o moc_optionsettime.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/VentiApp/bin || mkdir -p $(INSTALL_ROOT)/opt/VentiApp/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/VentiApp/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/VentiApp/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/VentiApp/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

